/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as HistoricoSenhaRouteImport } from './routes/historico-senha'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as IndexRouteImport } from './routes/index'

const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoSenhaRoute = HistoricoSenhaRouteImport.update({
  id: '/historico-senha',
  path: '/historico-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/historico-senha': typeof HistoricoSenhaRoute
  '/instalar': typeof InstalarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/historico-senha': typeof HistoricoSenhaRoute
  '/instalar': typeof InstalarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historico': typeof HistoricoRoute
  '/historico-senha': typeof HistoricoSenhaRoute
  '/instalar': typeof InstalarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/historico' | '/historico-senha' | '/instalar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historico' | '/historico-senha' | '/instalar'
  id: '__root__' | '/' | '/historico' | '/historico-senha' | '/instalar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoricoRoute: typeof HistoricoRoute
  HistoricoSenhaRoute: typeof HistoricoSenhaRoute
  InstalarRoute: typeof InstalarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico-senha': {
      id: '/historico-senha'
      path: '/historico-senha'
      fullPath: '/historico-senha'
      preLoaderRoute: typeof HistoricoSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoricoRoute: HistoricoRoute,
  HistoricoSenhaRoute: HistoricoSenhaRoute,
  InstalarRoute: InstalarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
